version: "3.5"

networks:
  wikijs:
  wikijs-private:

volumes:
  wikijs:
  wikijs-repo:
  wikijs-db:

secrets:
  wikijs_admin_password:
    name: ${STACK_NAME:-technocore}_wikijs_admin_password
    external: true
  wikijs_ssh_key:
    name: ${STACK_NAME:-technocore}_wikijs_ssh_key
    external: true
  wikijs_wikijs_db_password:
    name: ${STACK_NAME:-technocore}_wikijs_wikijs_db_password
    external: true
  wikijs_db_wikijs_password:
    name: ${STACK_NAME:-technocore}_wikijs_db_wikijs_password
    external: true

services:
  ingress:
    networks:
      - wikijs

  wikijs:
    deploy:
      labels:
        - traefik.frontend.rule=$WIKIJS_ROUTING_LABEL
        - traefik.frontend.priority=$WIKIJS_ROUTING_LABEL_PRIORITY
        - traefik.port=3000
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_wikijs
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
      - DB_TYPE=postgres
      - DB_HOST=wikijs_db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS={{"{{DOCKER-SECRET:wikijs_db_password}}"}}
      - DB_NAME=wikijs
      - HOST=https://wikijs.$DOMAIN
      - WIKI_PORT=3000
      - WIKI_TITLE=Wiki JS
    image: ${image_provider:-scififarms}/technocore-wikijs:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - wikijs
      - wikijs-private
    secrets:
      - source: wikijs_wikijs_db_password
        target: wikijs_db_password
      - source: wikijs_admin_password
        target: admin_password
      - source: wikijs_ssh_key
        target: ssh_key
    volumes:
      - wikijs:/wiki/data/
      - wikijs-repo:/wiki/repo
      - ${DEV_MOUNT_WIKIJS_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  wikijs_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    #environment:
    environment:
      - POSTGRES_USER=wikijs
      - POSTGRES_PASSWORD={{"{{DOCKER-SECRET:wikijs_password}}"}}
      - POSTGRES_DB=wikijs
    #image: ${image_provider:-scififarms}/technocore-wikijs-db:${TAG:-latest}
    image: ${image_provider:-scififarms}/technocore-farmbot-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - wikijs-private
    secrets:
      #- source: wikijs_db_admin_password
      #  target: admin_password
      - source: wikijs_db_wikijs_password
        target: wikijs_password
    volumes:
      - wikijs-db:/var/lib/postgresql/data
